#kubectl apply -f demo-k8s-pod.yml
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  labels:
    app: web
spec:
    containers:
      - name: demo
        image: gkalmardocker/demo:latest
        ports:
          - containerPort: 8080
        env:
          - name: PROFILE
            value: "test"
          - name: MONGODB_CONNECTION_STRING
            value: "mongodb://root:example@192.168.0.19:27017/test"
      - name: mongo
        image: mongo
        ports:
          - containerPort: 27017mongodb_connection_string
